apiVersion: apps/v1
kind: Deployment
metadata:
  name: tim-weather-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tim-weather-api
  template:
    metadata:
      labels:
        app: tim-weather-api
    spec:
      containers:
      - name: tim-weather-api
        image: vramakacr1.azurecr.io/weatherapi
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
    name: tim-weather-api
    labels:
        app: tim-weather-api
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: tim-weather-api